defmodule Nexus.Shared.Middleware.CorrelationId do
  @moduledoc """
  Middleware to inject a deterministic Correlation ID into command metadata.
  Ensures every event generated by this command inherits the tracing token.
  """
  @behaviour Commanded.Middleware

  alias Commanded.Middleware.Pipeline

  @spec before_dispatch(Pipeline.t()) :: Pipeline.t()
  def before_dispatch(%Pipeline{} = pipeline) do
    metadata = pipeline.metadata || %{}

    correlation_id =
      Map.get(metadata, "correlation_id") || Map.get(metadata, :correlation_id) ||
        Uniq.UUID.uuid7()

    causation_id =
      Map.get(metadata, "causation_id") || Map.get(metadata, :causation_id) || correlation_id

    updated_metadata =
      metadata
      |> Map.put("correlation_id", correlation_id)
      |> Map.put("causation_id", causation_id)
      |> Map.put(:correlation_id, correlation_id)
      |> Map.put(:causation_id, causation_id)

    %{pipeline | metadata: updated_metadata}
  end

  @spec after_dispatch(Pipeline.t()) :: Pipeline.t()
  def after_dispatch(%Pipeline{} = pipeline), do: pipeline

  @spec after_failure(Pipeline.t()) :: Pipeline.t()
  def after_failure(%Pipeline{} = pipeline), do: pipeline
end
